resources:
- name: wordpress-apacheRepo_docker
  type: GitRepo
  configuration:
    gitProvider: Github_Sander
    path: wordpress-apache
    files:
      include: "Dockerfile"
 
- name: wordpress-apacheDockerImage
  type: Image
  configuration:
    registry: docker-local
    imageName: shesselink81/wordpress-apache
    imageTag: latest
 
- name: wordpress-apacheRepo_chart
  type: GitRepo
  configuration:
    gitProvider: Github_Sander
    path: helm-charts/wordpress-apache
    files:
      include: "*.*"
 
- name: wordpress-apacheChart
  type: HelmChart
  configuration:
    sourceArtifactory: art
    repository: wordpress-apacheChart
    chart: wordpress-apache
    version: 0.1.0
pipelines:
  - name: helm_full_flow
    steps:
      - name: build_image
        type: DockerBuild
        configuration:
          affinityGroup: buildAndPush
          integrations:
            - name: art-docker-local
          inputResources:
            - name: wordpress-apacheRepo_docker
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: shesselink81/wordpress-apache
          dockerImageTag: $run_number
 
      - name: push_image
        type: DockerPush
        configuration:
          affinityGroup: buildAndPush
          integrations:
            - name: art-docker-local
          targetRepository: shesselink81/wordpress-apache
          inputSteps:
            - name: build_image
          outputResources:
            - name: wordpress-apacheDockerImage
 
      - name: publish_helm_chart
        type: HelmPublish
        configuration:
          inputResources:
            - name: wordpress-apacheRepo_chart
          outputResources:
            - name: wordpress-apacheRepo_chart
          chartPath: ./wordpress-apache
 
      - name: deploy_helm_chart
        type: HelmDeploy
        configuration:
          integrations:
            - name: tr_kubernetes
          inputResources:
            - name: wordpress-apacheChart
            - name: wordpress-apacheDockerImage
          releaseName: wordpress-apache
          flags: "--namespace dev"
          valueFilePaths:
            - values.yaml
